github:
  features:
    issues: false  # disable issues since it's archived
  archived: true   # mark as archived

notifications:
  commits: commits@maven.apache.org
  issues: issues@maven.apache.org
  pullrequests: issues@maven.apache.org
